development:
  adapter: postgresql
  encoding: utf8
  database: townhall_dev
  username: postgres
  password: 
  host: localhost # not mandatory
  pool: 5 # not mandatory
  timeout: 5000 # not mandatory