production:
  adapter: postgresql
  database: townhall_production
  host: localhost
development:
  adapter: postgresql
  database: townhall_dev
  host: localhost
test:
  adapter: postgresql
  database: townhall_test
  host: localhost
